"""add appointments table and user security question fields

Revision ID: 00400aba8f05
Revises: 32bbff731361
Create Date: 2026-07-08 15:18:58.696078

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '00400aba8f05'
down_revision: Union[str, None] = '32bbff731361'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('appointments',
    sa.Column('appointment_id', sa.Integer(), nullable=False),
    sa.Column('circle_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('time', sa.Time(), nullable=True),
    sa.Column('location', sa.Text(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['circle_id'], ['family_circles.circle_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('appointment_id')
    )
    op.create_index(op.f('ix_appointments_appointment_id'), 'appointments', ['appointment_id'], unique=False)
    op.add_column('users', sa.Column('security_question', sa.Text(), nullable=True))
    op.add_column('users', sa.Column('security_answer_hash', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'security_answer_hash')
    op.drop_column('users', 'security_question')
    op.drop_index(op.f('ix_appointments_appointment_id'), table_name='appointments')
    op.drop_table('appointments')
    # ### end Alembic commands ###
