"""add plaid_items table for bank account linking

Revision ID: 1baa3bab0dc9
Revises: 72a53fe34816
Create Date: 2026-07-14 14:06:31.890759

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1baa3bab0dc9'
down_revision: Union[str, None] = '72a53fe34816'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('plaid_items',
    sa.Column('plaid_item_id', sa.Integer(), nullable=False),
    sa.Column('circle_id', sa.Integer(), nullable=False),
    sa.Column('item_id', sa.Text(), nullable=False),
    sa.Column('access_token', sa.Text(), nullable=False),
    sa.Column('institution_name', sa.Text(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['circle_id'], ['family_circles.circle_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('plaid_item_id'),
    sa.UniqueConstraint('item_id')
    )
    op.create_index(op.f('ix_plaid_items_plaid_item_id'), 'plaid_items', ['plaid_item_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_plaid_items_plaid_item_id'), table_name='plaid_items')
    op.drop_table('plaid_items')
    # ### end Alembic commands ###
