"""add security question lockout to users

Revision ID: 1ce5c6e50907
Revises: ab9c75a0a934
Create Date: 2026-07-28 14:53:24.575819

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1ce5c6e50907'
down_revision: Union[str, None] = 'ab9c75a0a934'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('security_question_attempts', sa.Integer(), server_default='0', nullable=False))
    op.add_column('users', sa.Column('security_question_locked_until', sa.TIMESTAMP(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'security_question_locked_until')
    op.drop_column('users', 'security_question_attempts')
    # ### end Alembic commands ###
