"""create initial 9 tables

Revision ID: 32bbff731361
Revises: 
Create Date: 2026-07-08 07:16:22.859341

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '32bbff731361'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('email', sa.Text(), nullable=False),
    sa.Column('password_hash', sa.Text(), nullable=False),
    sa.Column('full_name', sa.Text(), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('phone', sa.Text(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('user_id'),
    sa.UniqueConstraint('email')
    )
    op.create_index(op.f('ix_users_user_id'), 'users', ['user_id'], unique=False)
    op.create_table('family_circles',
    sa.Column('circle_id', sa.Integer(), nullable=False),
    sa.Column('elder_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['elder_id'], ['users.user_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('circle_id')
    )
    op.create_index(op.f('ix_family_circles_circle_id'), 'family_circles', ['circle_id'], unique=False)
    op.create_table('accounts',
    sa.Column('account_id', sa.Integer(), nullable=False),
    sa.Column('circle_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('category', sa.Text(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('last_reviewed_at', sa.TIMESTAMP(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=True),
    sa.CheckConstraint("category IN ('bank', 'insurance', 'healthcare', 'government', 'pharmacy', 'other')", name='accounts_category_check'),
    sa.ForeignKeyConstraint(['circle_id'], ['family_circles.circle_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('account_id')
    )
    op.create_index(op.f('ix_accounts_account_id'), 'accounts', ['account_id'], unique=False)
    op.create_table('bills',
    sa.Column('bill_id', sa.Integer(), nullable=False),
    sa.Column('circle_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('due_date', sa.Date(), nullable=False),
    sa.Column('is_paid', sa.Boolean(), nullable=True),
    sa.Column('category', sa.Text(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['circle_id'], ['family_circles.circle_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('bill_id')
    )
    op.create_index(op.f('ix_bills_bill_id'), 'bills', ['bill_id'], unique=False)
    op.create_table('circle_members',
    sa.Column('membership_id', sa.Integer(), nullable=False),
    sa.Column('circle_id', sa.Integer(), nullable=False),
    sa.Column('caregiver_id', sa.Integer(), nullable=False),
    sa.Column('can_view_bills', sa.Boolean(), nullable=True),
    sa.Column('can_view_prescriptions', sa.Boolean(), nullable=True),
    sa.Column('can_view_accounts', sa.Boolean(), nullable=True),
    sa.Column('can_view_flags', sa.Boolean(), nullable=True),
    sa.Column('accepted_at', sa.TIMESTAMP(), nullable=True),
    sa.ForeignKeyConstraint(['caregiver_id'], ['users.user_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['circle_id'], ['family_circles.circle_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('membership_id')
    )
    op.create_index(op.f('ix_circle_members_membership_id'), 'circle_members', ['membership_id'], unique=False)
    op.create_table('flags',
    sa.Column('flag_id', sa.Integer(), nullable=False),
    sa.Column('circle_id', sa.Integer(), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('type', sa.Text(), nullable=True),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('severity', sa.Text(), nullable=True),
    sa.Column('is_resolved', sa.Boolean(), nullable=True),
    sa.Column('resolved_at', sa.TIMESTAMP(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=True),
    sa.CheckConstraint("severity IN ('low', 'high')", name='flags_severity_check'),
    sa.CheckConstraint("type IN ('call', 'email', 'text', 'bill', 'other')", name='flags_type_check'),
    sa.ForeignKeyConstraint(['circle_id'], ['family_circles.circle_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['created_by'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('flag_id')
    )
    op.create_index(op.f('ix_flags_flag_id'), 'flags', ['flag_id'], unique=False)
    op.create_table('notes',
    sa.Column('note_id', sa.Integer(), nullable=False),
    sa.Column('circle_id', sa.Integer(), nullable=False),
    sa.Column('author_id', sa.Integer(), nullable=True),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['author_id'], ['users.user_id'], ),
    sa.ForeignKeyConstraint(['circle_id'], ['family_circles.circle_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('note_id')
    )
    op.create_index(op.f('ix_notes_note_id'), 'notes', ['note_id'], unique=False)
    op.create_table('prescriptions',
    sa.Column('prescription_id', sa.Integer(), nullable=False),
    sa.Column('circle_id', sa.Integer(), nullable=False),
    sa.Column('medication_name', sa.Text(), nullable=False),
    sa.Column('dosage', sa.Text(), nullable=True),
    sa.Column('prescribing_doctor', sa.Text(), nullable=True),
    sa.Column('pharmacy_name', sa.Text(), nullable=True),
    sa.Column('refill_date', sa.Date(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['circle_id'], ['family_circles.circle_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('prescription_id')
    )
    op.create_index(op.f('ix_prescriptions_prescription_id'), 'prescriptions', ['prescription_id'], unique=False)
    op.create_table('subscriptions',
    sa.Column('subscription_id', sa.Integer(), nullable=False),
    sa.Column('circle_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('monthly_cost', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('last_reviewed_at', sa.TIMESTAMP(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['circle_id'], ['family_circles.circle_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('subscription_id')
    )
    op.create_index(op.f('ix_subscriptions_subscription_id'), 'subscriptions', ['subscription_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_subscriptions_subscription_id'), table_name='subscriptions')
    op.drop_table('subscriptions')
    op.drop_index(op.f('ix_prescriptions_prescription_id'), table_name='prescriptions')
    op.drop_table('prescriptions')
    op.drop_index(op.f('ix_notes_note_id'), table_name='notes')
    op.drop_table('notes')
    op.drop_index(op.f('ix_flags_flag_id'), table_name='flags')
    op.drop_table('flags')
    op.drop_index(op.f('ix_circle_members_membership_id'), table_name='circle_members')
    op.drop_table('circle_members')
    op.drop_index(op.f('ix_bills_bill_id'), table_name='bills')
    op.drop_table('bills')
    op.drop_index(op.f('ix_accounts_account_id'), table_name='accounts')
    op.drop_table('accounts')
    op.drop_index(op.f('ix_family_circles_circle_id'), table_name='family_circles')
    op.drop_table('family_circles')
    op.drop_index(op.f('ix_users_user_id'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
