"""add digest frequency preference to circle members

Revision ID: 5b8d590e3394
Revises: 1baa3bab0dc9
Create Date: 2026-07-22 14:28:44.862251

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5b8d590e3394'
down_revision: Union[str, None] = '1baa3bab0dc9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('circle_members', sa.Column('digest_frequency', sa.Text(), server_default='weekly', nullable=False))
    op.add_column('circle_members', sa.Column('last_digest_sent_at', sa.TIMESTAMP(), nullable=True))
    op.create_check_constraint(
        'circle_members_digest_frequency_check',
        'circle_members',
        "digest_frequency IN ('off', 'daily', 'weekly', 'biweekly', 'monthly')",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('circle_members_digest_frequency_check', 'circle_members', type_='check')
    op.drop_column('circle_members', 'last_digest_sent_at')
    op.drop_column('circle_members', 'digest_frequency')
    # ### end Alembic commands ###
