"""add circle_invitations table for inviting non-registered people

Revision ID: 72a53fe34816
Revises: 773977aec681
Create Date: 2026-07-13 14:15:44.071366

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '72a53fe34816'
down_revision: Union[str, None] = '773977aec681'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('circle_invitations',
    sa.Column('invitation_id', sa.Integer(), nullable=False),
    sa.Column('circle_id', sa.Integer(), nullable=False),
    sa.Column('email', sa.Text(), nullable=False),
    sa.Column('can_view_bills', sa.Boolean(), nullable=True),
    sa.Column('can_view_prescriptions', sa.Boolean(), nullable=True),
    sa.Column('can_view_accounts', sa.Boolean(), nullable=True),
    sa.Column('can_view_flags', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=True),
    sa.Column('accepted_at', sa.TIMESTAMP(), nullable=True),
    sa.ForeignKeyConstraint(['circle_id'], ['family_circles.circle_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('invitation_id')
    )
    op.create_index(op.f('ix_circle_invitations_invitation_id'), 'circle_invitations', ['invitation_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_circle_invitations_invitation_id'), table_name='circle_invitations')
    op.drop_table('circle_invitations')
    # ### end Alembic commands ###
