"""add ai risk assessment to flags

Revision ID: f2d4be7d57a5
Revises: 5b8d590e3394
Create Date: 2026-07-23 14:41:40.437124

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f2d4be7d57a5'
down_revision: Union[str, None] = '5b8d590e3394'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('flags', sa.Column('ai_risk_level', sa.Text(), nullable=True))
    op.add_column('flags', sa.Column('ai_explanation', sa.Text(), nullable=True))
    op.add_column('flags', sa.Column('ai_suggested_action', sa.Text(), nullable=True))
    op.add_column('flags', sa.Column('ai_assessed_at', sa.TIMESTAMP(), nullable=True))
    op.create_check_constraint(
        'flags_ai_risk_level_check', 'flags', "ai_risk_level IN ('low', 'medium', 'high')",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('flags_ai_risk_level_check', 'flags', type_='check')
    op.drop_column('flags', 'ai_assessed_at')
    op.drop_column('flags', 'ai_suggested_action')
    op.drop_column('flags', 'ai_explanation')
    op.drop_column('flags', 'ai_risk_level')
    # ### end Alembic commands ###
